version: "3.8"

services:
  web:
    build: .
    image: django-docker
    env_file:
      - .env
    ports:
      - 80:8080
    depends_on:
      - db
    networks:
      - django

  db:
    image: postgres
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - django

networks:
  django:

volumes:
  pgdata:
