version: '3.8'

services:
  db:
    image: postgres
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - django
    restart: always

  web:
    build: .
    env_file:
      - .env
    ports:
      - 8080:8080
    depends_on:
      - db
    networks:
      - django
    restart: always

  www:
    build: ./nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/lib/letsencrypt:/var/lib/letsencrypt
    depends_on:
      - web
    networks:
      - django
    restart: always

networks:
  django:

volumes:
  pgdata:
