name: django-docker

services:
- name: web
  github:
    repo: connorsullivan/django-docker
    branch: main
    deploy_on_push: true
  dockerfile_path: Dockerfile
  envs:
  - key: DJANGO_SETTINGS_MODULE
    value: core.settings.prod
    scope: RUN_AND_BUILD_TIME
  - key: DJANGO_ALLOWED_HOSTS
    value: .ondigitalocean.app
    scope: RUN_TIME
  - key: DATABASE_URL
    value: 'sqlite://:memory:'
    scope: RUN_TIME
  instance_size_slug: basic-xxs
  instance_count: 1
  http_port: 8080
  routes:
  - path: /

region: nyc
